### ISSUE TITLE
trivy is failing - helm charts vulnerabilities

### ISSUE THREAD

**Issue by akocbek** [terraform-ibm-modules/terraform-ibm-mas#16]
### Description

`trivy` pre-commit tool is failing for helm charts inside `chart` folder. Created a new [PR](https://github.com/terraform-ibm-modules/terraform-ibm-mas/pull/15) where `.trivyignore` file  was added to ignore those linting errors. Please review it

error:
```

2024-02-27T17:45:29.492Z	INFO	Misconfiguration scanning is enabled
2024-02-27T17:45:29.492Z	INFO	Need to update the built-in policies
2024-02-27T17:45:29.492Z	INFO	Downloading the built-in policies...
45.79 KiB / 45.79 KiB [-----------------------------------------------------------] 100.00% ? p/s 0s2024-02-27T17:45:34.738Z	INFO	Detected config files: 4

chart/deploy-mas/templates/01-deploy-mas.yaml (helm)
====================================================
Tests: 139 (SUCCESSES: 125, FAILURES: 14, EXCEPTIONS: 0)
Failures: 14 (UNKNOWN: 0, LOW: 9, MEDIUM: 4, HIGH: 1, CRITICAL: 0)

MEDIUM: Container 'mas-deploy' of Job 'mas-deploy-sync-role' should set 'securityContext.allowPrivilegeEscalation' to false
════════════════════════════════════════
A program inside the container can elevate its own privileges and run as root, which might give the program control over the container and node.

See https://avd.aquasec.com/misconfig/ksv001
────────────────────────────────────────
 chart/deploy-mas/templates/01-deploy-mas.yaml:36-124
────────────────────────────────────────
  36 ┌         - name: mas-deploy
  37 │           image: quay.io/ibmmas/cli:7.14.0-pre.master
  38 │           imagePullPolicy: Always
  39 │           #volumeMounts:
  40 │           #  - mountPath: "/usr/config-pvc"
  41 │           #    name: pv-storage
  42 │           command:
  43 │             - /bin/sh
  44 └             - -c
  ..   
────────────────────────────────────────


LOW: Container 'mas-deploy' of Job 'mas-deploy-sync-role' should add 'ALL' to 'securityContext.capabilities.drop'
════════════════════════════════════════
The container should drop all default capabilities and add only those that are needed for its execution.

See https://avd.aquasec.com/misconfig/ksv003
────────────────────────────────────────
 chart/deploy-mas/templates/01-deploy-mas.yaml:36-124
────────────────────────────────────────
  36 ┌         - name: mas-deploy
  37 │           image: quay.io/ibmmas/cli:7.14.0-pre.master
  38 │           imagePullPolicy: Always
  39 │           #volumeMounts:
  40 │           #  - mountPath: "/usr/config-pvc"
  41 │           #    name: pv-storage
  42 │           command:
  43 │             - /bin/sh
  44 └             - -c
  ..   
────────────────────────────────────────


LOW: Container 'mas-deploy' of Job 'mas-deploy-sync-role' should set 'resources.limits.cpu'
════════════════════════════════════════
Enforcing CPU limits prevents DoS via resource exhaustion.
 chart/deploy-mas/templates/01-deploy-mas.yaml:36-124
────────────────────────────────────────
  36 ┌         - name: mas-deploy
  37 │           image: quay.io/ibmmas/cli:7.14.0-pre.master
  38 │           imagePullPolicy: Always
  39 │           #volumeMounts:
  40 │           #  - mountPath: "/usr/config-pvc"
  41 │           #    name: pv-storage
  42 │           command:
  43 │             - /bin/sh
  44 └             - -c
  ..   
────────────────────────────────────────


MEDIUM: ClusterRoleBinding 'sync-sa' should not bind to roles ["cluster-admin", "admin", "edit"]
════════════════════════════════════════
Either cluster-admin or those granted powerful permissions.

See https://avd.aquasec.com/misconfig/ksv111
────────────────────────────────────────
 chart/deploy-mas/templates/01-deploy-mas.yaml:5-6
────────────────────────────────────────
   5 ┌   name: sync-sa
   6 └   namespace: mas-inst1-pipelines
────────────────────────────────────────


2024-02-27T17:45:34.776Z	INFO	Misconfiguration scanning is enabled
2024-02-27T17:45:35.338Z	INFO	Detected config files: 1
2024-02-27T17:45:35.382Z	INFO	Misconfiguration scanning is enabled
2024-02-27T17:45:35.950Z	INFO	Detected config files: 1
```

**Comment by padmankosalaram** [comment]
PR - https://github.com/terraform-ibm-modules/terraform-ibm-mas/pull/28/
Above PR fixed 7 Low, 4 Medium violations.


Currently there are 2 Low and 1 High. 
There are few technical challenge to fix these violations and working with @hvetsa to take it forward

Failures: 3 (UNKNOWN: 0, LOW: 2, MEDIUM: 0, HIGH: 1, CRITICAL: 0)

**Comment by padmankosalaram** [comment]
Shared the recording and write up details with @hvetsa. Currently review is in progress with Connal and Todd

Details of recording and write up captured in https://jsw.ibm.com/browse/MASHYPER-92

**Comment by ocofaigh** [comment]
@NatarajBTI There are still some being ignored in https://github.com/terraform-ibm-modules/terraform-ibm-mas/blob/main/.trivyignore
Since you guys own the helm chart, I suggest you create issues for the outstanding items if you don’t plan to address them for GA. Then maybe add a code comment in the .trivyignore file which links to each issue, Some of them however your not going to want to GA with. For example, nothing should be deployed to the default namespace as per https://github.com/terraform-ibm-modules/terraform-ibm-mas/blob/e5e5924206e7b498f06619f5dcbb017dee02e5f1/.trivyignore#L23

**Comment by padmankosalaram** [comment]
Hi @ocofaigh 


As discussed, we have 4 open trivy issues, created separate issue for each issue and .trivyignore file was updated with their tracking issue #.  

PR: https://github.com/terraform-ibm-modules/terraform-ibm-mas/pull/89
In the same PR  `KSV104` reference (which was earlier code commented ) was removed to avoid confusion


Below are the open trivy and their issue #. These issues will be updated with their respective technical justification.

KSV014 - https://github.com/terraform-ibm-modules/terraform-ibm-mas/issues/85

KSV020 - https://github.com/terraform-ibm-modules/terraform-ibm-mas/issues/86 

KSV021 - https://github.com/terraform-ibm-modules/terraform-ibm-mas/issues/87

KSV111 - https://github.com/terraform-ibm-modules/terraform-ibm-mas/issues/88


Closing issue https://github.com/terraform-ibm-modules/terraform-ibm-mas/issues/16
