### ISSUE TITLE
Provision File storage

### ISSUE THREAD

**Issue by padmankosalaram** [terraform-ibm-modules/terraform-ibm-mas#17]
### Description

- ROKS provisioned via DA has only block storage.
- We have a requirement that requires File storage. 
- Good to have File storage installation as part of (post) steps in ROKS provision process

### New or affected modules

Not sure 

---

By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/terraform-ibm-modules/documentation/blob/main/CODE_OF_CONDUCT.md)

**Comment by vburckhardt** [comment]
Opened the request at https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone/issues/729 . The file storageclass are added by the file storage addon. https://cloud.ibm.com/docs/openshift?topic=openshift-storage-file-vpc-apps

**Comment by NatarajBTI** [comment]
![image](https://github.com/terraform-ibm-modules/terraform-ibm-mas/assets/57617912/695be121-5e09-4db8-a42c-5ec5722a978e)

![image](https://github.com/terraform-ibm-modules/terraform-ibm-mas/assets/57617912/76a8cf42-12b0-4f3e-92e4-3c1cd4cf1c30)

![image](https://github.com/terraform-ibm-modules/terraform-ibm-mas/assets/57617912/6721782f-0d3a-4b56-90d1-6fb3c28fa134)

I was able to resolve this file storage issue by enabing the file storage add-on by following steps here --> https://cloud.ibm.com/docs/containers?topic=containers-storage-file-vpc-install

I used ibmc-vpc-file-dp2 storage class for rwx operations needed for db2 and pipeline run was successful in all tasks. @vburckhardt @padmankosalaram

**Comment by ocofaigh** [comment]
@NatarajBTI your going to wan't to ensure that the override json you add to the repo that your docs will reference includes the config to provision the file storage addon

**Comment by NatarajBTI** [comment]
[override_FileStorage.json](https://github.com/terraform-ibm-modules/terraform-ibm-mas/files/15228507/override_FileStorage.json)

This issue is now resolved by adding the below entry in override.json file. Attached override.json file used above.
"addons": { "vpc-file-csi-driver": "1.2" }
