### ISSUE TITLE
Need info on connected ROKS DA and MAS DA as stack on catalog

### ISSUE THREAD

**Issue by NatarajBTI** [terraform-ibm-modules/terraform-ibm-mas#24]
@vburckhardt - Could you please reply to below queries on connected ROKS and MAS DA.

1) How the input parameter values page will be shown to the end-user? Is both ROKS DA input variables and MAS DA input variables will be shown on the initial page of deployment? Are the input values entered by user on the respective DA's input parameter sections will be passed onto the respective DA's?
2) Is the ROKS cluster Id is passed onto MAS DA automatically? or MAS DA code should read it from output file of ROKS DA?
3) How the deployment failure condition is handled? If ROKS DA deployment fails then it should exit the entire stack deployment without further invoking MAS DA right? Even if it invokes MAS DA, it will fail because of connectivity issue to ROKS cluster.
4) I am seeing some delay in ROKS web console coming up even after it says ROKS DA is deployed successfully and it showing "Normal" state on IBM Cloud's OpenShift clusters section..This should be handled because MAS DA shouldn't fail with connectivity issue to ROKS cluster due to this delay. We connect using terraform code & hope all the required services are up for successful connection to happen and to proceed further.

**Comment by vburckhardt** [comment]
1. All or a subset of the inputs will be available. It is really up to the stack author to decide which variables are exposed. The values are then passed automatically to each DA as they are executed (akin to the environment concept in Project today)
2. The wiring of the clusterId into the MAS DA is done by Project through the concept of references. https://cloud.ibm.com/docs/secure-enterprise?topic=secure-enterprise-config-project&interface=ui#reference-values
3. Correct, exit the entire execution. Execution can then be resumed.
4. We could add an additional script that waits for the console to be served. Currently the script only wait for the ingress to be green.

**Comment by NatarajBTI** [comment]
@vburckhardt - On the 2nd point above ("The wiring of the clusterId into the MAS DA is done by Project through the concept of references."), do you know any other TIM reference to share with us where this is implemented?
