### ISSUE TITLE
Seeing error while selecting the secrets manager instances on Projects page

### ISSUE THREAD

**Issue by NatarajBTI** [terraform-ibm-modules/terraform-ibm-mas#57]
![image](https://github.com/terraform-ibm-modules/terraform-ibm-mas/assets/57617912/4a4b53ca-8af0-41c4-85cb-93633c9ac6e0)

Seeing "Error loading providers" while I am trying to enter the sensitive values using the secrets manager instances on Projects page.
Please see above screenshot.

I came to know that this defect --> https://github.ibm.com/ibmcloud/projects-ui/issues/1894
is opened for the same issue but I don't have access to view the same.

**Comment by padmankosalaram** [comment]
Noticed `Error loading secrets` error while I verify it today. 

Screenshot below.
![image-1](https://github.com/terraform-ibm-modules/terraform-ibm-mas/assets/45054700/8f40d976-4b59-43d9-8b96-f2bf84d05da1)

**Comment by ocofaigh** [comment]
This should be fixed no on prod, so going to close this. If you reproduce, please re-open and we can engage with Projects team
