### ISSUE TITLE
Wait until mas install has completed before returning 

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/terraform-ibm-mas#6]
### Description

The current version of the DA deploys the manifests needed to _kick off_ the install process, and returns immediately after. Ideally the DA should wait until the install is complete (or fails) before returning. This will also enable returning urls to the deployment, etc

There is an example of similar pattern at https://github.ibm.com/GoldenEye/ocp-service-mesh-module/blob/0bcad9fc95328eac2050c0d0ccdb0306404edc22/main.tf#L190 - using a script invoked from terraform that waits until the SM operator is functional. A similar conceptual approach could be implemented - eg: confirm-mas-operational.sh

**Comment by ocofaigh** [comment]
Being addressed in https://github.com/terraform-ibm-modules/terraform-ibm-mas/pull/56

**Comment by NatarajBTI** [comment]
This was addressed long time back and it waits for outcome of MAS install and in case of failure, it exits with non-zero code & in case of success in deployment, it outputs the MAS admin URL. Hence closing this issue.
