### ISSUE TITLE
Unskip upgrade test

### ISSUE THREAD

**Issue by ocofaigh** [terraform-ibm-modules/terraform-ibm-mas#64]
After https://github.com/terraform-ibm-modules/terraform-ibm-mas/pull/56 is merged, the upgrade test should be enabled by removing this line of code: `t.Skip("Skipping upgrade test until solution is in the main branch")` from `tests/pr_test.go`

**Comment by NatarajBTI** [comment]
@ocofaigh - Can we close this issue? as #56 is merged now..

**Comment by ocofaigh** [comment]
@NatarajBTI Nope, the upgrade test has not yet been enabled. We can enabled it after we determine the GA release version

**Comment by NatarajBTI** [comment]
@NatarajBTI - Ok..thanks..So is this issue a candidate to be deferred?

**Comment by ocofaigh** [comment]
Don't defer it - as soon as we identify release candidate (hopefully today), we will enable the upgrade test

**Comment by ocofaigh** [comment]
I can create a PR for this today

**Comment by ocofaigh** [comment]
PR: https://github.com/terraform-ibm-modules/terraform-ibm-mas/pull/108
