### ISSUE TITLE
getAdminURL.py bugs

### ISSUE THREAD

**Issue by daniel-butler-irl** [terraform-ibm-modules/terraform-ibm-mas#66]
`getAdminURL.py` does not initalize`varstr` This causes the script to fail if no routes are found. 
The script needs to exit with non-zero exit code on failure to let Terraform know it has failed.

`result` may not have been initialized either.

**Comment by ocofaigh** [comment]
Being addressed in https://github.com/terraform-ibm-modules/terraform-ibm-mas/pull/56
