### ISSUE TITLE
Ensure all resources are removed after an undeploy

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/terraform-ibm-mas#7]
### Description

There are manual steps currently needed to undeploy the DA.

```
oc delete project mas-inst1-pipelines
oc delete project ibm-sls
helm delete  mas-deploy-v1
helm list --all --all-namespaces
helm uninstall maximo-operator-catalog-helm-release --namespace default
```

Those steps should be ideally done as part of the helm uninstall triggered through the terraform destroy.

**Comment by ocofaigh** [comment]
This should be already handled by the helm provider - will close once https://github.com/terraform-ibm-modules/terraform-ibm-mas/pull/56 is merged

**Comment by ocofaigh** [comment]
Should be verified in latest version

**Comment by NatarajBTI** [comment]
Code in this uninstall helm chart (with pre-delete hook) does the uninstall of deployed MAS instance & then the helm release is uninstalled. This is verified in latest version too. Hence closing this issue.
