### ISSUE TITLE
Destroy is not destroying block storage for VPC instances that are created by DA

### ISSUE THREAD

**Issue by ocofaigh** [terraform-ibm-modules/terraform-ibm-mas#78]
Destroy is not destroying block storage for VPC instances that are created by DA. After terraform destroy is run, all resource created by the DA should be deleted, but it seems these are not. Example:

```
% ic resource service-instances --type all -g core-hygcif-workload-rg              
Retrieving instances with all types in resource group core-hygcif-workload-rg in all locations under account GoldenEye GoldenEye Development's Account as ocofaigh@ie.ibm.com...
OK
Name                                       Location     State    Type                Resource Group ID
pvc-1058107b-490d-40ac-8653-1b006f801d48   us-south-1   active   resource_instance   f0b2fa3331144f56b9d4572285299604
pvc-15435e82-6291-4b87-9289-e656bba273b8   us-south-1   active   resource_instance   f0b2fa3331144f56b9d4572285299604
pvc-2dd4c8d4-cbe0-42fc-bb3c-eb7a13ff5854   us-south-2   active   resource_instance   f0b2fa3331144f56b9d4572285299604
pvc-57d3b859-281f-4823-a745-0338cd6255f5   us-south-2   active   resource_instance   f0b2fa3331144f56b9d4572285299604
pvc-5db2d51f-4965-4f0e-92ff-aa5fe76ad537   us-south-1   active   resource_instance   f0b2fa3331144f56b9d4572285299604
pvc-66c4d396-fdcd-4d4a-820e-ee6184fda289   us-south-2   active   resource_instance   f0b2fa3331144f56b9d4572285299604
pvc-800d86c3-72c3-4513-b2a9-e2d2daf474cd   us-south-2   active   resource_instance   f0b2fa3331144f56b9d4572285299604
pvc-91ba0652-9fca-4349-ac7e-40d8f6638f08   us-south-2   active   resource_instance   f0b2fa3331144f56b9d4572285299604
pvc-ce789131-a406-4161-9610-567057850363   us-south-1   active   resource_instance   f0b2fa3331144f56b9d4572285299604
pvc-e14457f2-3a56-468d-a621-950031376ee8   us-south-2   active   resource_instance   f0b2fa3331144f56b9d4572285299604
pvc-e556c9d9-d986-460f-8172-620c8fac5b29   us-south-2   active   resource_instance   f0b2fa3331144f56b9d4572285299604
pvc-e5f3c8aa-9fb5-4f5a-b38a-2e7f524d24ca   us-south-1   active   resource_instance   f0b2fa3331144f56b9d4572285299604
pvc-e7d14d7a-b0f3-4446-9e86-379089a69a05   us-south-2   active   resource_instance   f0b2fa3331144f56b9d4572285299604
pvc-ec80ec23-061a-422c-bbe5-227bb907357b   us-south-1   active   resource_instance   f0b2fa3331144f56b9d4572285299604
pvc-ed12604a-c006-45b4-abcb-b2739ea39e74   us-south-2   active   resource_instance   f0b2fa3331144f56b9d4572285299604
pvc-fb2ec5d5-c5e2-4ff0-8e46-c0432c6e71d1   us-south-1   active   resource_instance   f0b2fa3331144f56b9d4572285299604
```

![image](https://github.com/terraform-ibm-modules/terraform-ibm-mas/assets/29608224/0a5f9dc0-80a2-4ab5-ad79-6cbf049f5484)

FYI, It means that the PR tests will always fail on destroy too

**Comment by ocofaigh** [comment]
@NatarajBTI Actually I'm not sure that MAS should ever expose the ability to clean them up. I think if the user choice to delete persistent storage when deleting the cluster, these would get cleaned up. Terraform also has the ability to pick this option when provisioning clusters, however I found we have not exposed it in landing zone. I created an [issue](https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone/issues/780) to expose it in landing zone so we can use it for the tests so they don't fail. For now Ill push a workaround so tests pass until we expose this feature.

**Comment by ocofaigh** [comment]
@NatarajBTI can you link to the documentation for this to see if we are good to close this?

**Comment by NatarajBTI** [comment]
![image](https://github.com/terraform-ibm-modules/terraform-ibm-mas/assets/57617912/c8fb5613-6c63-46ff-897a-3a29e0a1a1a7)
Link --> https://test.cloud.ibm.com/docs-draft/maximo-application-suite?topic=maximo-application-suite-deploying-da

@ocofaigh - Please see the above screenshot or in above link & that's the note we have added in our documentation. Pasting the note below:
"Tip: After you uninstall the application, some persistent volumes remain. You can choose to either retain or manually remove the data."
