### ISSUE TITLE
Add test cases

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/terraform-ibm-mas#8]
### Description

Update examples under https://github.com/terraform-ibm-modules/terraform-ibm-mas/tree/main/examples
and call those examples under test https://github.com/terraform-ibm-modules/terraform-ibm-mas/tree/main/tests

**Comment by NatarajBTI** [comment]
@vburckhardt - Please give us more details on what testcases (examples) we should add here. We support two different offerings for the end user to select for deployment namely, MAS Core and MAS Core+Manage. So should we split the code for these offerings and add them as examples? I tried referring other TIMs but not getting.
