### ISSUE TITLE
[intermittent] Helm release "maximo-helm-release" was created but has a failed status

### ISSUE THREAD

**Issue by ocofaigh** [terraform-ibm-modules/terraform-ibm-mas#90]
The below issue was seen in a pipeline run. Since the cluster was destroyed we have no way to know why the job failed, however going to keep this issue open to track such failures to see how frequently this occurs.
Full log: https://github.com/terraform-ibm-modules/terraform-ibm-mas/actions/runs/8941604181/job/24562462524

Summary:
```
TestRunDACore 2024-05-03T16:55:40Z logger.go:66: │ Warning: Helm release "maximo-helm-release" was created but has a failed status. Use the `helm` command to investigate the error, correct it, then run Terraform again.
TestRunDACore 2024-05-03T16:55:40Z logger.go:66: │ 
TestRunDACore 2024-05-03T16:55:40Z logger.go:66: │   with module.existing_cluster.helm_release.maximo_helm_release,
TestRunDACore 2024-05-03T16:55:40Z logger.go:66: │   on ../../main.tf line 8, in resource "helm_release" "maximo_helm_release":
TestRunDACore 2024-05-03T16:55:40Z logger.go:66: │    8: resource "helm_release" "maximo_helm_release" {
TestRunDACore 2024-05-03T16:55:40Z logger.go:66: │ 
TestRunDACore 2024-05-03T16:55:40Z logger.go:66: ╵
TestRunDACore 2024-05-03T16:55:40Z logger.go:66: ╷
TestRunDACore 2024-05-03T16:55:40Z logger.go:66: │ Error: job is failed: mas-inst1-pipelines/mas-deploy-job
TestRunDACore 2024-05-03T16:55:40Z logger.go:66: │ 
TestRunDACore 2024-05-03T16:55:40Z logger.go:66: │   with module.existing_cluster.helm_release.maximo_helm_release,
TestRunDACore 2024-05-03T16:55:40Z logger.go:66: │   on ../../main.tf line 8, in resource "helm_release" "maximo_helm_release":
TestRunDACore 2024-05-03T16:55:40Z logger.go:66: │    8: resource "helm_release" "maximo_helm_release" {
TestRunDACore 2024-05-03T16:55:40Z logger.go:66: │ 
TestRunDACore 2024-05-03T16:55:40Z logger.go:66: ╵
```

**Comment by ocofaigh** [comment]
cc @NatarajBTI

**Comment by NatarajBTI** [comment]
Unable to recreate this issue in automated infra tests I executed as detailed below:

1st attempt  (successful): 
Link to Infra test -->  https://github.com/terraform-ibm-modules/terraform-ibm-mas/actions/runs/8948698762

![image](https://github.com/terraform-ibm-modules/terraform-ibm-mas/assets/57617912/fddf4f9e-d4f2-4a96-a8e9-aa45523559dc)

![image (322)](https://github.com/terraform-ibm-modules/terraform-ibm-mas/assets/57617912/c741e13d-ea57-4419-aeb7-cc4d8a29bb10)
![image (321)](https://github.com/terraform-ibm-modules/terraform-ibm-mas/assets/57617912/fac3c4f4-ec6e-482f-bd05-1bce89506b85)

2nd attempt (successful)

Link to infra test: https://github.com/terraform-ibm-modules/terraform-ibm-mas/actions/runs/8966128953

![image](https://github.com/terraform-ibm-modules/terraform-ibm-mas/assets/57617912/e3bdc1fa-2b32-4f90-ab6e-704ceaee1324)

**Comment by NatarajBTI** [comment]
Based on the results of infra tests of two different attempts as posted above, this issue is not recreatable.

**Comment by ocofaigh** [comment]
Reproduced -> https://github.com/terraform-ibm-modules/terraform-ibm-mas/actions/runs/8946518936/job/24577343472

**Comment by NatarajBTI** [comment]
![image](https://github.com/terraform-ibm-modules/terraform-ibm-mas/assets/57617912/f5f30387-477c-4d1b-a51e-d17fa6982568)

Okay, here it's failed because it hasn't exited after pipeline task failure & has tried to fetch adminURL this behavior can't be reproduced elsewhere (that's while executing on private catalog, projects page, or from command prompt).

**Comment by NatarajBTI** [comment]
![image](https://github.com/terraform-ibm-modules/terraform-ibm-mas/assets/57617912/ba21bd90-b6fe-4373-b598-286c81e51e34)

![image](https://github.com/terraform-ibm-modules/terraform-ibm-mas/assets/57617912/bb2e424f-8d2b-4ece-9065-683f6e8dd5f9)

![image](https://github.com/terraform-ibm-modules/terraform-ibm-mas/assets/57617912/74545cba-15fd-4c41-abf1-fc002a7cb8e9)

![image (323)](https://github.com/terraform-ibm-modules/terraform-ibm-mas/assets/57617912/5d90ec92-550c-4d3b-8a85-464862086312)

![image](https://github.com/terraform-ibm-modules/terraform-ibm-mas/assets/57617912/5d91665e-944f-4039-bebb-9c7bb1223e62)

Here is the run from Projects page & it exited the deployment when the pipeline failed. This deployment was made to fail by entering storage class names with which it will fail.

**Comment by NatarajBTI** [comment]
@ocofaigh - Can we close this issue? as the MAS DA deployment is stable now and if we start using Openshift 4.14, these intermittent issue shouldn't be seen as IKS team as mentioned 4.14 and later uses Konnectivity & update window of master is less because of that. I am okay if we have to test it with 4.14 version for some runs and then close this issue based on the result of those runs.
If that's the case then can we defer this issue? Thanks

**Comment by ocofaigh** [comment]
Agree - issue was related to the health of the cluster. Since the docs will specify the cluster must be healthy before deploying, I'm going to close this
