### ISSUE TITLE
Merge the test catalog into the partner centre MAS catalog

### ISSUE THREAD

**Issue by NatarajBTI** [terraform-ibm-modules/terraform-ibm-mas#93]
Merge the test catalog into the partner centre MAS catalog

**Comment by NatarajBTI** [comment]
Adjust the CI/CD pipeline to use the partner centre catalog.

**Comment by ocofaigh** [comment]
@NatarajBTI The partner centre and catalog is in your account - please work with your team here. Un-assigning myself.

**Comment by NatarajBTI** [comment]
![image](https://github.com/terraform-ibm-modules/terraform-ibm-mas/assets/57617912/a4b13bb3-2c75-4ba1-a38d-675fce449dbe)

This merging of test catalog into the partner center's catalog is complete. Hence closign this issue.
